import { useState } from 'react';
import { Link } from 'react-router-dom';
import { toast } from 'sonner';
import api from '../../../lib/axios';
import { formatRupiah, formatDate } from '../../../lib/finance';

const input = 'w-full rounded-lg border border-slate-200 p-2 text-sm';
const button = 'rounded-lg bg-emerald-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-50';
const emptyItem = () => ({ uraian: '', volume: 1, satuan: 'paket', hargaSatuan: '', kategoriId: '' });
const editable = ['DISETUJUI','DICAIRKAN_SEBAGIAN','DICAIRKAN_PENUH','REALISASI','PERLU_REVISI','DALAM_PENYESUAIAN'];

export default function PenyesuaianRab({ rab, user, categories, accounts, onSaved }) {
  const [mode, setMode] = useState('');
  const [reason, setReason] = useState('');
  const [items, setItems] = useState([]);
  const [receipt, setReceipt] = useState({ tanggal: new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Makassar' }), jenisSumber: 'PUNIA' });
  const [busy, setBusy] = useState(false);
  const treasurer = ['BENDAHARA','SUPER_ADMIN'].includes(user?.role);
  const canEdit = editable.includes(rab.status);
  const send = async (url, data) => {
    setBusy(true);
    try { const res = await api.post(`/keuangan/${url}`, data); toast.success(res.data.message); setMode(''); setReason(''); await onSaved(); }
    catch (e) { toast.error(e.response?.data?.message || 'Gagal menyimpan'); }
    finally { setBusy(false); }
  };
  const receive = () => { const data = new FormData(); Object.entries(receipt).forEach(([k,v]) => { if (v != null && v !== '') data.append(k,v); }); send(`rab/${rab.id}/pencairan`, data); };
  const pending = rab.perubahanAnggarans?.filter(p => p.status === 'MENUNGGU_VERIFIKASI') || [];
  return <section className="space-y-4 rounded-2xl border border-emerald-100 bg-white p-5 shadow-sm">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold text-slate-800">Dana Tambahan & Penyesuaian</h2><p className="mt-1 text-xs text-slate-500">Dana tambahan menambah kas setelah verifikasi. Perubahan anggaran memerlukan persetujuan terpisah.</p></div><Link className="text-sm font-semibold text-emerald-700" to="/admin/keuangan/rekonsiliasi">Laporan Rekonsiliasi →</Link></div>
    <div className="grid gap-3 sm:grid-cols-3">{[['Bendahara',rab.ringkasan.pencairanBendahara],['Hibah / Punia / Lainnya',rab.ringkasan.danaTambahan],['Penerimaan Menunggu',rab.ringkasan.penerimaanMenunggu]].map(([label,value]) => <div key={label} className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className="font-bold text-slate-800">{formatRupiah(value)}</p></div>)}</div>
    <div className="flex flex-wrap gap-2">
      {rab.status === 'SELESAI' && user?.role === 'SUPER_ADMIN' && <button disabled={busy} className={button} onClick={() => setMode('reopen')}>Buka Penyesuaian RAB / LPJ</button>}
      {canEdit && <><button disabled={busy} className={button} onClick={() => { setReceipt({ tanggal: new Date().toLocaleDateString('en-CA', { timeZone: 'Asia/Makassar' }), jenisSumber: 'PUNIA', akunKasId: accounts[0]?.id || '' }); setMode('receive'); }}>Tambah Dana Masuk</button><button disabled={busy || !!pending.length} className={button} onClick={() => { setItems(rab.items.map(i => ({ id:i.id, kategoriId:i.kategoriId || '', uraian:i.uraian, volume:Number(i.volume), satuan:i.satuan, hargaSatuan:Number(i.hargaSatuan) }))); setMode('budget'); }}>Sesuaikan Komponen Anggaran</button></>}
    </div>
    {rab.status === 'DALAM_PENYESUAIAN' && <p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-800">Revisi {rab.revision} sedang disesuaikan. Setelah transaksi dan komponen diverifikasi, ajukan LPJ kembali untuk persetujuan dengan QR baru.</p>}
    {rab.pencairans.filter(r => r.status === 'MENUNGGU_VERIFIKASI').map(row => <div key={row.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3"><div><p className="font-semibold">{row.jenisSumber} · {formatRupiah(row.nominal)}</p><p className="text-xs text-slate-500">{formatDate(row.tanggal)} · {row.sumberDana} · {row.akunKas?.nama}</p><p className="text-xs text-amber-700">Menunggu verifikasi — belum menambah kas</p></div>{treasurer && canEdit && <button className={button} disabled={busy} onClick={() => { setReceipt(row); setMode('verify'); }}>Periksa Penerimaan</button>}</div>)}
    {pending.map(p => <div key={p.id} className="rounded-lg border border-amber-200 p-3"><p className="font-semibold">Penyesuaian anggaran menunggu persetujuan</p><p className="text-sm text-slate-500">{p.alasan}</p><ul className="my-3 space-y-1 text-sm">{p.items.map((i,index) => <li key={index}>{i.id ? 'Ubah' : 'Tambah'}: {i.uraian} — {formatRupiah(i.jumlahDiajukan)}</li>)}</ul>{treasurer && canEdit && <button disabled={busy} className={button} onClick={() => { setReceipt({ proposalId:p.id }); setMode('decision'); }}>Periksa & Putuskan</button>}</div>)}
    {!!rab.arsips?.length && <div><h3 className="mb-2 text-sm font-bold">Arsip LPJ Sebelumnya</h3>{rab.arsips.map(a => <Link key={a.id} className="mb-2 block rounded-lg bg-slate-50 p-3 text-sm text-emerald-800" to={`/admin/keuangan/rab/${rab.id}?arsip=${a.id}`}>Revisi {a.revision} · {formatDate(a.createdAt)} — {a.alasan} · Lihat / Export PDF</Link>)}</div>}
    {mode && <div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-slate-950/60 p-4 md:p-10"><div className="w-full max-w-3xl space-y-4 rounded-2xl bg-white p-5"><div className="flex justify-between"><h3 className="font-bold">{({ reopen:'Buka Penyesuaian', budget:'Penyesuaian Komponen Anggaran', receive:'Dana Masuk', verify:'Verifikasi Penerimaan', decision:'Persetujuan Anggaran' })[mode]}</h3><button disabled={busy} onClick={() => setMode('')}>Tutup</button></div>
      {mode === 'reopen' && <p className="text-sm text-slate-600">LPJ saat ini disimpan sebagai arsip beserta data persetujuannya. Revisi baru memerlukan persetujuan ulang.</p>}
      {mode === 'budget' && <div className="space-y-3">{items.map((item,index) => <div key={index} className="grid grid-cols-2 gap-2 rounded-lg bg-slate-50 p-3"><label className="col-span-2 text-xs">Uraian<input disabled={!!item.id && user?.role !== 'SUPER_ADMIN'} className={input} value={item.uraian} onChange={e => setItems(items.map((r,i) => i===index ? {...r,uraian:e.target.value}:r))}/></label>{[['volume','Volume'],['satuan','Satuan'],['hargaSatuan','Harga Satuan']].map(([key,label]) => <label key={key} className="text-xs">{label}<input className={input} type={key==='satuan'?'text':'number'} step={key==='volume'?'0.01':'1'} min="0" value={item[key]} onChange={e => setItems(items.map((r,i) => i===index ? {...r,[key]:e.target.value}:r))}/></label>)}<label className="text-xs">Kategori<select className={input} value={item.kategoriId} onChange={e => setItems(items.map((r,i) => i===index ? {...r,kategoriId:e.target.value}:r))}><option value="">Tanpa kategori</option>{categories.map(c=><option key={c.id} value={c.id}>{c.nama}</option>)}</select></label>{!item.id && <button className="text-left text-xs text-red-600" onClick={() => setItems(items.filter((_,i) => i!==index))}>Hapus komponen baru</button>}</div>)}<button className={button} onClick={() => setItems([...items,emptyItem()])}>+ Komponen Baru</button></div>}
      {['reopen','budget','decision'].includes(mode) && <label className="block text-sm">Alasan / Catatan<textarea rows={3} className={input} value={reason} onChange={e => setReason(e.target.value)}/></label>}
      {mode === 'receive' && <div className="grid gap-3 sm:grid-cols-2">{[['tanggal','Tanggal','date'],['nominal','Nominal','number'],['sumberDana','Pemberi / Asal Dana','text'],['nomorReferensi','No. Referensi','text']].map(([key,label,type]) => <label key={key} className="text-sm">{label}<input type={type} className={input} value={receipt[key]||''} onChange={e=>setReceipt({...receipt,[key]:e.target.value})}/></label>)}<label className="text-sm">Jenis Sumber<select className={input} value={receipt.jenisSumber} onChange={e=>setReceipt({...receipt,jenisSumber:e.target.value})}>{['BENDAHARA','HIBAH','PUNIA','LAINNYA'].map(s=><option key={s}>{s}</option>)}</select></label><label className="text-sm">Kas Penerima<select className={input} value={receipt.akunKasId||''} onChange={e=>setReceipt({...receipt,akunKasId:e.target.value})}><option value="">Pilih kas</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.nama}</option>)}</select></label><label className="text-sm">Keterangan<textarea className={input} value={receipt.keterangan||''} onChange={e=>setReceipt({...receipt,keterangan:e.target.value})}/></label><label className="text-sm">Bukti<input type="file" accept=".pdf,.jpg,.jpeg,.png" className={input} onChange={e=>setReceipt({...receipt,bukti:e.target.files[0]})}/></label></div>}
      {mode === 'verify' && <div className="space-y-2 text-sm"><p>{formatDate(receipt.tanggal)} · {receipt.jenisSumber} · {receipt.sumberDana}</p><p className="text-xl font-bold">{formatRupiah(receipt.nominal)}</p><p>Kas: {receipt.akunKas?.nama}</p><p>Referensi: {receipt.nomorReferensi || '-'}</p><p>{receipt.keterangan}</p><p>Bukti tersedia pada bagian Dokumen & Bukti Transaksi.</p><label>Alasan pembatalan (jika ditolak)<textarea className={input} value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy || reason.trim().length < 5} className="text-red-700" onClick={() => send(`pencairan/${receipt.id}/cancel`, {alasan:reason})}>Tolak / Batalkan</button></div>}
      <div className="flex gap-2"><button disabled={busy || (['reopen','budget','decision'].includes(mode) && reason.trim().length < 5)} className={button} onClick={() => mode==='reopen'?send(`rab/${rab.id}/reopen`,{alasan:reason}):mode==='budget'?send(`rab/${rab.id}/penyesuaian-anggaran`,{items,alasan:reason}):mode==='receive'?receive():mode==='verify'?send(`pencairan/${receipt.id}/verify`,{}):send(`penyesuaian-anggaran/${receipt.proposalId}/decision`,{status:'DISETUJUI',alasan:reason})}>{busy?'Memproses...':mode==='verify'?'Verifikasi & Tambah Kas':mode==='decision'?'Setujui':'Simpan'}</button>{mode==='decision' && <button disabled={busy || reason.trim().length < 5} className="text-red-700" onClick={()=>send(`penyesuaian-anggaran/${receipt.proposalId}/decision`,{status:'DITOLAK',alasan:reason})}>Tolak Penyesuaian</button>}</div>
    </div></div>}
  </section>;
}
