-- TRUNCATE tabel dengan CASCADE untuk menangani foreign keys
-- RESTART IDENTITY akan meriset urutan ID (autoincrement) kembali ke 1

TRUNCATE TABLE "AbsensiSisya" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SesiAbsensi" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Pembayaran" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "SisyaProgram" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "Sisya" RESTART IDENTITY CASCADE;
