const express = require('express');
const controller = require('../controllers/keuangan.controller');
const reconciliation = require('../controllers/rekonsiliasi.controller');
const { atomicFinanceWrite } = require('../services/finance-db');
const upload = require('../middlewares/upload.middleware');
const { requireAuth, requireFinanceAccess, requireTreasurer, requireSuperAdmin } = require('../middlewares/auth.middleware');

const router = express.Router();
router.use(requireAuth, requireFinanceAccess);

router.get('/dashboard', controller.getDashboard);
router.get('/rekonsiliasi', reconciliation.report);
router.get('/rekonsiliasi/export.xlsx', reconciliation.exportExcel);
router.get('/rekonsiliasi/kas', reconciliation.cashChecks);
router.post('/rekonsiliasi/kas', requireTreasurer, atomicFinanceWrite(reconciliation.saveCashCheck));
router.post('/rab/:id/reopen', atomicFinanceWrite(reconciliation.reopen));
router.get('/rab/:id/arsip/:archiveId', reconciliation.archive);
router.post('/rab/:id/penyesuaian-anggaran', atomicFinanceWrite(reconciliation.proposeBudget));
router.post('/penyesuaian-anggaran/:id/decision', requireTreasurer, atomicFinanceWrite(reconciliation.decideBudget));
router.post('/pencairan/:id/verify', requireTreasurer, atomicFinanceWrite(reconciliation.verifyReceipt));
router.get('/verification-documents', controller.listVerificationDocuments);
router.get('/kategori', controller.listCategories);
router.get('/akun-kas', controller.listAccounts);
router.post('/kategori', requireTreasurer, atomicFinanceWrite(controller.saveCategory));
router.patch('/kategori/:id', requireTreasurer, atomicFinanceWrite(controller.saveCategory));
router.post('/akun-kas', requireTreasurer, atomicFinanceWrite(controller.saveAccount));
router.patch('/akun-kas/:id', requireTreasurer, atomicFinanceWrite(controller.saveAccount));

router.get('/rab', controller.listRab);
router.post('/rab', upload.single('dokumen'), atomicFinanceWrite(controller.createRab));
router.get('/rab/:id/export.xlsx', controller.exportExcel);
router.get('/rab/:id', controller.getRab);
router.patch('/rab/:id/items/:itemId/uraian', requireSuperAdmin, atomicFinanceWrite(reconciliation.editItemDescription));
router.patch('/rab/:id', upload.single('dokumen'), atomicFinanceWrite(controller.updateRab));
router.patch('/rab/:id/metadata', requireTreasurer, atomicFinanceWrite(controller.updateRabMetadata));
router.post('/rab/:id/submit', atomicFinanceWrite(controller.submitRab));
router.post('/rab/:id/approve', requireTreasurer, atomicFinanceWrite(controller.approveRab));
router.post('/rab/:id/reject', requireTreasurer, atomicFinanceWrite(controller.rejectRab));
router.post('/rab/:id/pencairan', upload.single('bukti'), atomicFinanceWrite(reconciliation.receive));
router.post('/rab/:id/pengeluaran', upload.single('bukti'), atomicFinanceWrite(controller.addExpense));
router.post('/rab/:id/pengembalian', requireTreasurer, upload.single('bukti'), atomicFinanceWrite(controller.addReturn));
router.post('/rab/:id/submit-lpj', atomicFinanceWrite(controller.submitLpj));
router.post('/rab/:id/request-revision', requireTreasurer, atomicFinanceWrite(controller.requestRevision));
router.post('/rab/:id/close', requireTreasurer, atomicFinanceWrite(controller.closeRab));
router.post('/rab/:id/sign-lpj', requireTreasurer, atomicFinanceWrite(controller.signCompletedLpj));
router.post('/rab/:id/sign-rab', requireTreasurer, atomicFinanceWrite(controller.signAdjustedRab));
router.patch('/rab/:id/dokumen', upload.single('bukti'), atomicFinanceWrite(controller.updateRabEvidence));

router.post('/pencairan/:id/cancel', requireTreasurer, atomicFinanceWrite(controller.cancelDisbursement));
router.patch('/pencairan/:id/bukti', upload.single('bukti'), atomicFinanceWrite(controller.updateDisbursementEvidence));
router.patch('/pengeluaran/:id', requireTreasurer, upload.single('bukti'), atomicFinanceWrite(controller.updateExpense));
router.patch('/pengeluaran/:id/bukti', upload.single('bukti'), atomicFinanceWrite(controller.updateExpenseEvidence));
router.post('/pengeluaran/:id/verify', requireTreasurer, atomicFinanceWrite(controller.verifyExpense));
router.post('/pengeluaran/:id/reject', requireTreasurer, atomicFinanceWrite(controller.rejectExpense));
router.post('/pengeluaran/:id/cancel', requireTreasurer, atomicFinanceWrite(controller.cancelExpense));
router.post('/pengembalian/:id/cancel', requireTreasurer, atomicFinanceWrite(controller.cancelReturn));
router.patch('/pengembalian/:id/bukti', upload.single('bukti'), atomicFinanceWrite(controller.updateReturnEvidence));
router.get('/files/:filename', controller.serveFile);

module.exports = router;
